location_colors <- c(FUE = "#df982c",
                     RIO = "#59b2bf",
                     ZAM = "#ff10f0")
location_shapes <- c(FUE = 17,
                     RIO = 15,
                     ZAM = 16)
treatment_colors <- c(ECO ="#028900",
                      CON = "#602320",
                      ROT = "#1b85b8")
treatment_shapes <- c(ECO = 17,
                      ROT = 15,
                      CON = 16)
movement_colors <- c(MIN ="#028900",
                     YES = "#602320",
                     NO = "#1b85b8")
movement_shapes <- c(MIN = 17,
                     YES = 15,
                     NO = 16)